server:
    port: 8080
    contextPath: /meEconomiza
    tomcat:
        access_log_enabled: true
        basedir: target/tomcat

spring:
    application:
        name: meEconomiza
        version: 2017.1

    jpa:
        database: HSQL
        openInView: true
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    messageSource:
        cacheSeconds: 1    

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

application:
    social:
        google:
            clientId: 316087946070-9qge3fgub11tvvh1vl87jt6ell13l12f.apps.googleusercontent.com
            clientSecret: hcx0OxU-i2xMHYnr7Cbc3JF2
    security: 
            secureChannel: http
            key: meEconomiza