#!/usr/bin/env bash

heroku pg:psql --app savefy
\copy (SELECT * FROM CATEGORY) TO CATEGORY.csv CSV DELIMITER ','
\copy (SELECT * FROM SUBCATEGORY) TO SUBCATEGORY.csv CSV DELIMITER ','
\copy (SELECT * FROM ACCOUNT_ENTRY) TO ACCOUNT_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM ACCOUNT) TO ACCOUNT.csv CSV DELIMITER ','
\copy (SELECT * FROM BILL) TO BILL.csv CSV DELIMITER ','
\copy (SELECT * FROM BUDGET) TO BUDGET.csv CSV DELIMITER ','
\copy (SELECT * FROM BUDGET_ENTRY) TO BUDGET_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM INVESTMENT) TO INVESTMENT.csv CSV DELIMITER ','
\copy (SELECT * FROM INVESTMENT_ENTRY) TO INVESTMENT_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM INDEX) TO INDEX.csv CSV DELIMITER ','


