/**
* heroku pg:psql postgresql-convex-43609 --app savefy-staging < /Users/eriklacerda/Dev-Projects/savefy/postgresdb/helper/db-export-heroku-db.sql
**/


\copy (SELECT * FROM CATEGORY) TO CATEGORY.csv CSV DELIMITER ','
\copy (SELECT * FROM SUBCATEGORY) TO SUBCATEGORY.csv CSV DELIMITER ','
\copy (SELECT * FROM ACCOUNT_ENTRY) TO ACCOUNT_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM ACCOUNT) TO ACCOUNT.csv CSV DELIMITER ','
\copy (SELECT * FROM QUOTE_SALE) TO QUOTE_SALE.csv CSV DELIMITER ','
\copy (SELECT * FROM CONCILIATION_ENTRY) TO CONCILIATION_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM CONCILIATION) TO CONCILIATION.csv CSV DELIMITER ','
\copy (SELECT * FROM BENCHMARK) TO BENCHMARK.csv CSV DELIMITER ','
\copy (SELECT * FROM PATRIMONY_ENTRY) TO PATRIMONY_ENTRY.csv CSV DELIMITER ','
\copy (SELECT * FROM PATRIMONY) TO PATRIMONY.csv CSV DELIMITER ','
\copy (SELECT * FROM STOCK_SALE) TO STOCK_SALE.csv CSV DELIMITER ','
\copy (SELECT * FROM CATEGORY_PREDICTION) TO CATEGORY_PREDICTION.csv CSV DELIMITER ','
\copy (SELECT * FROM SANITIZE_PATTERN) TO SANITIZE_PATTERN.csv CSV DELIMITER ','
\copy (SELECT * FROM USER_PREFERENCES) TO USER_PREFERENCES.csv CSV DELIMITER ','
\copy (SELECT * FROM INSTITUTION) TO INSTITUTION.csv CSV DELIMITER ','
\copy (SELECT * FROM user_role) TO user_role.csv CSV DELIMITER ','
\copy (SELECT * FROM user_account) TO user_account.csv CSV DELIMITER ','
\copy (SELECT * FROM USER_GROUP) TO USER_GROUP.csv CSV DELIMITER ','
\copy (SELECT * FROM remember_me_token) TO remember_me_token.csv CSV DELIMITER ','